### PR TITLE
chore(lint): rsweb-6638 Sass Lint Class names

### PR DESCRIPTION
**Pull request by SyntaxStacks**
https://jira.rax.io/browse/RSWEB-6638

### CODE REVIEW

**Comment by bighappyface** [comment]
With the sass lint PR merged how are there 1675 problems failing this build?

**Comment by SyntaxStacks** [comment]
I removed the changes to the sass files and brought in sass-lint.

The builds have been failing since travis was integrated so there's not too much harm in that and after our adoption of maintainable css, I felt that it would be better to refactor the code to reflect that while correcting the lint issues. one thing that will have to be addressed is the max warning flag on the lint job. I have removed that flag in this PR to allow future bumps and commits.

**Comment by SyntaxStacks** [comment]
we can add `--max-warnings 0` back to the `sass-lint` npm script when we're ready to enforce sass-lint warnings as build failures

**Comment by bighappyface** [comment]
+1 on the convention update

Example of the regex in action http://refiddle.com/dzxm

**Pull request merged**
