### PR TITLE
feat (new pattern): dedicated configurator

### PR DESCRIPTION
**Pull request by runrog**

### CODE REVIEW

**Comment by ejchiefs** [comment]
screen shot 2018-11-09 at 4 13 56 pm

**Comment by WidgetsBurritos** [comment]
image

Hey should these prices line up in tablet mode too?

**Comment by WidgetsBurritos** [comment]
@ejchiefs Most excellent

**Comment by runrog** [comment]
New URL
http://mte-2884-dedicatedconfig.styleguide.dev.website.rackspace.com/derek/incubation/solutions

screen shot 2018-11-12 at 9 52 19 am

**Comment by WidgetsBurritos** [comment]
[run ci]

^ rebuilding ci environment

**Comment by WidgetsBurritos** [comment]
[run ci]

^ one more time.  had to undo a brand-refresh specific thing I changed in the pr builder

**Comment by WidgetsBurritos** [comment]
[run ci]

**Pull request merged**
