### PR TITLE
RSWEB-7415: adjusting background position to remediate cutting off…

### PR DESCRIPTION
**Pull request by amberRrucker**
RSWEB-7415

Needed to adjust background position for imac banners to keep the subject of our images from being cut off on the right.

### CODE REVIEW

**Comment by ejchiefs** [comment]
@amberRrucker This needs its own ticket (PR title does not contain JIRA ticket number)

**Comment by amberRrucker** [comment]
@ejchiefs done

**Comment by WidgetsBurritos** [comment]
👍

**Comment by runrog** [comment]
👍 Design review: subjects not cut off as expected
screen shot 2016-09-28 at 1 14 38 pm

**Comment by SyntaxStacks** [comment]
QE 👍

**Pull request merged**
