### PR TITLE
MTE-829: feat(new o365 tables): adding new custom pattern for o365 pricing tables

### PR DESCRIPTION
**Pull request by runrog**
preview: http://mte-829-o365table.styleguide.dev.website.rackspace.com/derek/incubation/homepage
Test is included for calculated the sticky header y value on scrolling.

### CODE REVIEW

**Comment by runrog** [comment]
@WidgetsBurritos and @brantdarilek this PR is a little lengthy so I'm requesting both of you guys on review and @amberRrucker for design review

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by amberRrucker** [comment]
@runrog 
These are the mocks for pricing on desktop and with scroll:
screen shot 2018-03-06 at 9 41 48 am
screen shot 2018-03-06 at 9 41 55 am
We should match those style-wise and text as well.
We need more padding in the header area on scroll. It's too tight. Fixing the text on scroll shoudl help there.

The logo is huge in medium screen sizes:
screen shot 2018-03-06 at 9 45 57 am

An example of a table cell: If we could put the paragraph beneath the title (example: Yammer) into p tags instead of an h4 that would improve clarity and reduce some of the table cell height.


If we could also add some padding above the table to separate the table from the tabs that would be nice.

**Comment by WidgetsBurritos** [comment]
[run ci]

^ Checking to see if this works now.

**Comment by runrog** [comment]
@amberRrucker I have taken care of your demands. Noting in here that we discussed the top padding issue being handled in the general.

Updated link: http://mte-829-o365table.styleguide.dev.website.rackspace.com/derek/incubation/homepage

**Pull request merged**
