### PR TITLE
RSWEB-8843: modularized footer as global component

### PR DESCRIPTION
**Pull request by runrog**
You can see footer on the following zoolander page:
http://localhost:9000/derek/incubation/homepage

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by runrog** [comment]
Hold off on merging this one. Forogt to modularize the landing page footer as well

**Comment by WidgetsBurritos** [comment]
@runrog no prob.  We're still waiting for a second review anyway

**Comment by runrog** [comment]
Ok changes made. proceed with design review @amberRrucker

**Comment by brantdarilek** [comment]
👍

**Pull request merged**
