### PR TITLE
Design

### PR DESCRIPTION
**Pull request by roycestewart**
initial merge of design

### CODE REVIEW

**Comment by bighappyface** [comment]
+1 coming along :)

**Comment by brady-vitrano** [comment]
@roycestewart I am adding the CDN fonts to the CSS. I will submit a PR to you to pull in these changes.

**Comment by bighappyface** [comment]
@brady-vitrano we may as well do that as a separate PR against this repo so we don't need to futz with modifying @roycestewart 's branch

Can you dig it?

**Comment by brady-vitrano** [comment]
@bighappyface fair enough! I will merge Royce branch and submit a PR immediately with the updates

**Pull request merged**
