### PR TITLE
MTE-5535: Solve PR builder wont build

### PR DESCRIPTION
**Pull request by xinbin**
https://jira.rax.io/browse/MTE-5535

### CODE REVIEW

**Comment by xinbin** [comment]
🙏

**Comment by xinbin** [comment]
[run ci]

**Comment by xinbin** [comment]
odd. not sure why the change to the install script didn't get committed on my 2nd commit, but running things locally I see this out put and running karma test, passes.

`> shared-karma-files@0.0.1 postinstall /Users/adri7917/workspace/zoolander/node_modules/karma-mocha/node_modules/shared-karma-files
> node ./bin/npm-postinstall

added 788 packages in 21.284s
Running "build:adapter" (build) task
>> Created lib/adapter.js`

**Comment by xinbin** [comment]
That magical adapter file was at least generated locally. let's see what happens here.

**Review by WidgetsBurritos — APPROVED** [review]
+1 LGTM

**Pull request merged**
