### PR TITLE
fix(global): link styles

### PR DESCRIPTION
**Pull request by amberRrucker**
RSWEB-8793

Wanted all links in text and generals to have the link style, not just top level. Ran into the problem where links are nested in lists and they arent styling.

### CODE REVIEW

**Comment by runrog** [comment]
👍 design

**Comment by WidgetsBurritos** [comment]
Can one of the admins verify this patch?

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
[run ci]

**Pull request merged**
