### PR TITLE
feat(derek): add customer story card

### PR DESCRIPTION
**Pull request by amberRrucker**
RSWEB-9717
Adding in the customer story resource card. A little different in structure from the rest of the cards.

Visible with the new document resource here:
http://localhost:3000/derek/view-templates/resource-center/refresh/resource-center

I would like to be able to see the vw font sizing with roger's new filter adjustments since we're breaking the cards at a different viewport.

### CODE REVIEW

**Comment by runrog** [comment]
Viewed these the other day +1

**Comment by writes** [comment]
+1

**Comment by writes** [comment]
+1 for https://github.com/rackerlabs/zoolander/pull/526/commits/e7bc5605ee3d690e3404d0f1d20e49fa6f1c03ff
https://github.com/rackerlabs/zoolander/pull/526/commits/d3e6d96cb4a0176bba0ee29fe1a74e1db2b2f250
https://github.com/rackerlabs/zoolander/pull/526/commits/db6c718a34f9f8a59923ef85c2d2a9f7d75f342e

**Comment by writes** [comment]
👍 

https://github.com/rackerlabs/zoolander/pull/526/commits/2620a852ce8723a02941d79c8fe161021e1cea3f
https://github.com/rackerlabs/zoolander/pull/526/commits/46dfdbbdf731e5cd65b86d744466e91a181c5262

**Comment by amberRrucker** [comment]
+1 on 
dd53434
9def60d
e7bc560
d3e6d96
db6c718

**Pull request merged**
