### PR TITLE
RSWEB-7416: awards-pattern

### PR DESCRIPTION
**Pull request by amberRrucker**
RSWEB-7416

Looking to add in the awards card. Need the scss for the imac pages.
Can be viewed either here:
http://localhost:9000/derek/examples/solutions

Or here with documentation:
http://localhost:9000/derek/examples/solutions-usage

Will attach an image or what it should look like. Just without the background image.

### CODE REVIEW

**Comment by amberRrucker** [comment]
screen shot 2016-09-27 at 3 16 21 pm

**Comment by WidgetsBurritos** [comment]
👍   - needs design review.  @runrog you got it?

**Comment by runrog** [comment]
👍 design
screen shot 2016-09-28 at 1 45 10 pm

**Comment by SyntaxStacks** [comment]
QE 👍

**Pull request merged**
