### PR TITLE
feat(landing-pages):first pass at landing page options

### PR DESCRIPTION
**Pull request by amberRrucker**
as well as video embed, form for lp, and documentation around those pages.
https://jira.rax.io/browse/RSWEB-6795

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
👍

**Comment by ejchiefs** [comment]
👍 knowing that more work will be done on the form variant

**Comment by WidgetsBurritos** [comment]
@SyntaxStacks There was an issue with the rebase on #203 so I had Amber just create a new PR.  EJ and I confirmed everything still looks good and +1'd it again.  The is pretty much all new style so should have little effect on www if merged.

**Comment by SyntaxStacks** [comment]
CTA
screen shot 2016-08-18 at 12 52 20 pm

Video
screen shot 2016-08-18 at 12 52 27 pm

Form
screen shot 2016-08-18 at 12 52 34 pm

**Comment by xinbin** [comment]
How do you kick off a retest? or what does one do when the "checks" have failed?

**Comment by SyntaxStacks** [comment]
@xinbin 
screen shot 2016-08-18 at 1 44 38 pm

**Comment by xinbin** [comment]
@amberRrucker hey you, can you resolve the conflicts for this guy?

**Comment by amberRrucker** [comment]
@xinbin I fixed the conflicts for this PR.

**Pull request merged**
