### PR TITLE
RSWEB-7224: update padding for value props

### PR DESCRIPTION
**Pull request by writes**
Updates padding for value props.

### CODE REVIEW

**Comment by amberRrucker** [comment]
The icon and hover color have both changed at some point and we need to fix that. Hover color should be gray-lighter and icon should be gray-darker.

**Comment by amberRrucker** [comment]
Do you mind adding some text length variation to one of these so we can make sure the equal height rows are working?

**Comment by writes** [comment]
@amberRrucker I added in one long one. Let me know if you see anything else. Thanks for the feedback!

**Comment by WidgetsBurritos** [comment]
👍

**Comment by amberRrucker** [comment]
Thank you. Looks good. +1
@WidgetsBurritos

**Pull request merged**
