### PR TITLE
refactor(nav): Remove margin from nav and add padding to body.

### PR DESCRIPTION
**Pull request by xinbin**
Note this is tied to a www pr

Change summary:
- Add new class for styling body region
- Remove margin from nav bar

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
@amberRrucker That's a design decision. I have no issues one way or another.

**Comment by amberRrucker** [comment]
I think it's a thing we need to do. Just want to get @ejchiefs sign off. I've also tagged him in the ticket.

**Comment by xinbin** [comment]
I'm fine with making a change, just looking for the go ahead :)

**Comment by xinbin** [comment]
Change made

**Pull request merged**
