### PR TITLE
feat(rsweb): use sass map for rsweb icon classes

### PR DESCRIPTION
**Pull request by bighappyface**
Any value in this?

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
Seems easier to read in my opinion.  Are there any other reasons for doing this or just general cleanup?

**Comment by brantdarilek** [comment]
Easier to read, IMO.

**Comment by bighappyface** [comment]
I saw a snippet months back about handling character fonts using a map and thought to add it here for fun.

**Comment by writes** [comment]
Like it

**Comment by WidgetsBurritos** [comment]
+1

**Pull request merged**
