### PR TITLE
fix(derek): Adjust condensed resource

### PR DESCRIPTION
**Pull request by amberRrucker**
@writes here is the quick fix for the condensed resource.

### CODE REVIEW

**Comment by writes** [comment]
@amberRrucker thanks!

**Comment by amberRrucker** [comment]
good call @runrog adjusted that.

**Comment by writes** [comment]
+1 LGTM

**Comment by writes** [comment]
@runrog can we get a quick Design Review?

**Comment by amberRrucker** [comment]
+1 to @runrog commit.

**Pull request merged**
