### PR TITLE
RSWEB-7901: Fixed Height IMAC Banners

### PR DESCRIPTION
**Pull request by amberRrucker**
RSWEB-7901
Adjusting the IMAC banners to have a fixed height. There are a couple concerns around length of title ect that is being addressed with content changes vs code changes.
Visible here:
http://localhost:9000/derek/incubation/imac
and any sandbox pages

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
screen shot 2017-01-06 at 1 17 25 pm

"BECAUSE ONE SIZE DOESN’T FIT ALL" indeed...

**Comment by WidgetsBurritos** [comment]
Also, since we're trying to get a bit more uniform and expected behavior out of this, what are your thoughts about just killing fittext as well?

**Comment by WidgetsBurritos** [comment]
More weirdness in mobile.  


image

**Comment by amberRrucker** [comment]
@WidgetsBurritos fittext still serves the purpose of scaling for different screen sizes and retaining the line breaks in the places they should be. I'd rather keep it and reduce risk for a relatively simple task. Also you're seeing the problems in that screen shot because you need khand installed on your system. There is a huge difference between arial and khand thats causing visual differences.

**Comment by WidgetsBurritos** [comment]
Not necessarily needing to be tackled now, but more for discussion. Should we set zoolander to load in khand like www does then? Because enforcing font dependencies on an individual system doesn't necessary make for friendly universal reviews.

**Comment by WidgetsBurritos** [comment]
I installed Khand.  The CTA is still falling off. 

image

**Comment by amberRrucker** [comment]
@WidgetsBurritos I'm going to get with Mike to see if we're utilizing the button at all in banners at this point. Remove it if we arent, adjust if we are.

**Comment by WidgetsBurritos** [comment]
👍 although now that there's a change to HTML markup, we're gonna need a `www` PR to go with this.

**Comment by amberRrucker** [comment]
@WidgetsBurritos theres a follow up ticket in for Roger already

**Comment by runrog** [comment]
@amberRrucker @WidgetsBurritos reviewing now. On the CTA in banner discussion. We are currently running a test on the homepage with a CTA in it. Since chats declined so much when it was removed we are seeing if there are any improvements. So we may in face be keeping them if so.

**Comment by amberRrucker** [comment]
@runrog yeah we already talked about all that last week. That's why we made two different options. One without the CTA and one with the CTA for homepage, why rack and landing pages.

**Comment by runrog** [comment]
@amber What about translation issues? I'm going to predict that some headers will be longer in other languages and cut off.

screen shot 2017-01-23 at 10 37 15 am
screen shot 2017-01-23 at 10 37 22 am

**Comment by amberRrucker** [comment]
@runrog feel free to run some of our headlines (homepage and why rack) through google translate to get a real estimate because I highly doubt it's going to add 5 lines ya crazy. We do have a character limit in english so try to use real headline options or stay within those character limits for examples please.

**Comment by runrog** [comment]
@amber if you say so. other than that, it looks good in all viewports. 👍

**Pull request merged**
