### PR TITLE
fix(karma-mocha): Resolve dependency issue with solve

### PR DESCRIPTION
**Pull request by WidgetsBurritos**
This PR fixes the dependency issue with solve.

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
[run ci]

**Review by xinbin — APPROVED** [review]
+1000

**Review by xinbin — APPROVED** [review]
hmm ill approve again?

**Comment by WidgetsBurritos** [comment]
This definitely got merged.  Not sure why it's saying the branch hasn't been deployed.  But it's fine.  I'm closing this.

**Pull request merged**
