### PR TITLE
RSWEB-7467: [bug] Adjust size of search button

### PR DESCRIPTION
**Pull request by WidgetsBurritos**
This PR adjusts search button size to fix issues with spanish.

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
Before:
screen shot 2016-10-05 at 10 52 01 am

After:
screen shot 2016-10-05 at 10 51 53 am

**Comment by runrog** [comment]
👍  design
Looks god in mobile as well
screen shot 2016-10-05 at 11 00 53 am

**Comment by WidgetsBurritos** [comment]
@SyntaxStacks, maybe but that would require refactoring as there are other issues in play here, which would need a separate ticket.  The bugfix task itself should simply fix the bug in question.

**Comment by SyntaxStacks** [comment]
I believe a task for size adjustment is the perfect time to refactor code that adjust to the size of the content. I'll defer to EJ on this as this is technically good to go.

**Pull request merged**
