### PR TITLE
RSWEB-7241: equal height fix to resource class

### PR DESCRIPTION
**Pull request by writes**
Updates resource class to ```display: flex;``` so that background will extend full height of the row.

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
👍

**Comment by amberRrucker** [comment]
In the PR description in the future can you include the page where its viewable - for posterity sake?

**Comment by amberRrucker** [comment]
+1 - looks good to me. Does anybody know when it broke?

**Comment by WidgetsBurritos** [comment]
@amberRrucker It came when we refactored these components a week or so ago. I wasn't able to use all the maintainable classes because how the grid patterns are so tightly coupled, so until they get decoupled we're gonna have some issues.

**Comment by writes** [comment]
Yep will do. I chose to put it in the ticket instead for this one since this is a public repo and the page is not yet live with an alias. I will remember for future pages that are currently live to add it in.

**Pull request merged**
