### PR TITLE
RSWEB-9534: New Homepage Banner

### PR DESCRIPTION
**Pull request by brantdarilek**
For review:
http://rsweb-9534-homepage.styleguide.dev.website.rackspace.com/derek/incubation/homepage

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
In mobile, the top box is slightly larger than the bottom box.  
image

For really wide browsers, the boxes stack on top of each other. 
image

Is this for sure the content here?  Basically, I just want to make sure, if the content was ever 2 lines or 4 lines instead, does the position of the container still look okay? It looks fine to me, but I just wanna make sure ya'll are okay with the alternatives. 
image

**Comment by WidgetsBurritos** [comment]
Is this too much padding on mobile? This is iphone 6 view.  Seems like the CTA shouldn't be below the fold here, but maybe that's just me.  
image

**Comment by brantdarilek** [comment]
@amberRrucker can I get your feedback on the spacing questions?

**Comment by brantdarilek** [comment]
`In mobile, the top box is slightly larger than the bottom box.`
@WidgetsBurritos the boxes are the exact same size what is different is the padding around the text going from 3 lines to 2 lines. @amberRrucker is this the desired look?

**Comment by WidgetsBurritos** [comment]
@brantdarilek,

No if you look closely at that screenshot again, there are two extra pixels on the top box, vs the smaller box. Also I just noticed on that screenshot the angled lines look a little off too: 
image
image

That said, can you confirm the code you just pushed up is correct, because now I'm seeing the boxes next to each other and mobile is just getting cut off. I'm not sure what's up with that, so I couldn't confirm the above was still an issue or not. 
image
image

**Comment by brantdarilek** [comment]
@WidgetsBurritos the code push was not correct. I've since made more adjustments with @amberRrucker on mobile. Would you mind reviewing once more. Thanks

**Pull request merged**
