### PR TITLE
refactor(button): update learning button style

### PR DESCRIPTION
**Pull request by xinbin**
Change summary:
- update learning button css

### CODE REVIEW

**Comment by xinbin** [comment]
http://rsweb-9121-learnmore-btn-changes.zoolander.dev.website.rackspace.com/office-365 
Has the button on it. Looks like this:
on hover:
on-hover
not on hover:  ;)
pattern_tests

**Comment by xinbin** [comment]
Did not know what color to use for on hover since it's not specified.

**Comment by xinbin** [comment]
[run ci]

**Comment by writes** [comment]
+1 QE

**Pull request merged**
